name: Continuos Integration

on:
  - push
  - pull_request

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm build
